spring.application.name=OSApiApplication
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/jbsc_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=jbsc
spring.datasource.password=2diSenai
spring.jpa.show.sql=True
